version: "3.5"
services:
#
# MARIADB
#
    mariadb-glpi: 
        build: mariadb/
        image: fametec/glpi:9.5.3-mariadb
        restart: unless-stopped
        volumes: 
          - mariadb-glpi-volume:/var/lib/mysql:rw
        env_file: ../.env 
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: ${MYSQL_GLPI_USER}
          MYSQL_PASSWORD: ${MYSQL_GLPI_PASSWORD}
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
        #ports: 
        #  - 3306:3306
        networks: 
          - glpi-backend
#
# GLPI
#
    glpi: 
        build: apache/
        image: fametec/glpi:9.5.3
        restart: unless-stopped
        volumes: 
          - glpi-volume-files:/var/www/html/files:rw
          - glpi-volume-plugins:/var/www/html/plugins:rw
        env_file: ../.env
        environment: 
          GLPI_LANG: pt_BR
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: ${MYSQL_GLPI_USER}
          MARIADB_PASSWORD: ${MYSQL_GLPI_PASSWORD}
          VERSION: "9.5.3"
          PLUGINS: "all"
        depends_on: 
          - mariadb-glpi
        ports: 
          - "8090:80"
        networks: 
          - glpi-frontend
          - glpi-backend
#
# CRON
#
    crond: 
        build: crond/
        image: fametec/glpi:9.5.3-crond
        restart: unless-stopped
        depends_on: 
          - glpi
          - mariadb-glpi
        env_file: ../.env
        environment: 
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: ${MYSQL_GLPI_USER}
          MARIADB_PASSWORD: ${MYSQL_GLPI_PASSWORD}
        # volumes: 
        #  - glpi-volume-files:/var/www/html/files:rw
        #  - glpi-volume-plugins:/var/www/html/plugins:rw
        networks: 
          - glpi-backend
#
# VOLUMES
#
volumes: 
  glpi-volume-files:
  glpi-volume-plugins:
  mariadb-glpi-volume: 
#
# NETWORKS
#
networks: 
  glpi-frontend: 
  glpi-backend:
