version: "3.5"
services:
    mariadb-glpi: 
        image: fametec/glpi:9.5.3-mariadb
        restart: unless-stopped
        volumes:
          - mariadb-glpi-volume:/var/lib/mysql:rw
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: glpi-user 
          MYSQL_PASSWORD: glpi-pass 
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
#       ports:
#         - 3306:3306
        networks: 
          - glpi-backend
#
#
    nginx: 
        build: nginx/
        image: fametec/glpi:9.5.3-nginx
        restart: unless-stopped
        volumes:
          - glpi-volume-files:/usr/share/nginx/html/glpi/files:rw
          - glpi-volume-plugins:/usr/share/nginx/html/glpi/plugins:rw
        depends_on: 
          - mariadb-glpi
          - php-fpm
        ports: 
          - 80:80
        networks: 
          - glpi-frontend
          - glpi-backend

    php-fpm: 
        build: php/
        image: fametec/glpi:9.5.3-php-fpm
        restart: unless-stopped
        environment:
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: glpi-user
          MARIADB_PASSWORD: glpi-pass
        volumes:
          - glpi-volume-files:/usr/share/nginx/html/glpi/files:rw
          - glpi-volume-plugins:/usr/share/nginx/html/glpi/plugins:rw
        depends_on:
          - mariadb-glpi
        networks:
          - glpi-backend
#        ports:
#          - 9000:9000
networks: 
    glpi-frontend: 
    glpi-backend:
#
volumes:
    glpi-volume-files:
    glpi-volume-plugins:
    mariadb-glpi-volume:
